//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldMap.MVC.RoleDataServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoleDataServiceReference.IRoleDataService")]
    public interface IRoleDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleDataService/Insert", ReplyAction="http://tempuri.org/IRoleDataService/InsertResponse")]
        void Insert(WorldMap.Model.RoleData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleDataService/Insert", ReplyAction="http://tempuri.org/IRoleDataService/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync(WorldMap.Model.RoleData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleDataService/Delete", ReplyAction="http://tempuri.org/IRoleDataService/DeleteResponse")]
        void Delete(WorldMap.Model.RoleData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleDataService/Delete", ReplyAction="http://tempuri.org/IRoleDataService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(WorldMap.Model.RoleData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleDataService/Update", ReplyAction="http://tempuri.org/IRoleDataService/UpdateResponse")]
        void Update(WorldMap.Model.RoleData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleDataService/Update", ReplyAction="http://tempuri.org/IRoleDataService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(WorldMap.Model.RoleData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleDataService/SelectAll", ReplyAction="http://tempuri.org/IRoleDataService/SelectAllResponse")]
        WorldMap.Model.RoleData[] SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleDataService/SelectAll", ReplyAction="http://tempuri.org/IRoleDataService/SelectAllResponse")]
        System.Threading.Tasks.Task<WorldMap.Model.RoleData[]> SelectAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleDataService/SelectById", ReplyAction="http://tempuri.org/IRoleDataService/SelectByIdResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorldMap.Model.RoleData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorldMap.Model.UserRoleMapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorldMap.Model.UserRoleMapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorldMap.Model.RoleData[]))]
        WorldMap.Model.RoleData SelectById(object id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleDataService/SelectById", ReplyAction="http://tempuri.org/IRoleDataService/SelectByIdResponse")]
        System.Threading.Tasks.Task<WorldMap.Model.RoleData> SelectByIdAsync(object id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoleDataServiceChannel : WorldMap.MVC.RoleDataServiceReference.IRoleDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoleDataServiceClient : System.ServiceModel.ClientBase<WorldMap.MVC.RoleDataServiceReference.IRoleDataService>, WorldMap.MVC.RoleDataServiceReference.IRoleDataService {
        
        public RoleDataServiceClient() {
        }
        
        public RoleDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoleDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoleDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoleDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Insert(WorldMap.Model.RoleData entity) {
            base.Channel.Insert(entity);
        }
        
        public System.Threading.Tasks.Task InsertAsync(WorldMap.Model.RoleData entity) {
            return base.Channel.InsertAsync(entity);
        }
        
        public void Delete(WorldMap.Model.RoleData entity) {
            base.Channel.Delete(entity);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(WorldMap.Model.RoleData entity) {
            return base.Channel.DeleteAsync(entity);
        }
        
        public void Update(WorldMap.Model.RoleData entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(WorldMap.Model.RoleData entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public WorldMap.Model.RoleData[] SelectAll() {
            return base.Channel.SelectAll();
        }
        
        public System.Threading.Tasks.Task<WorldMap.Model.RoleData[]> SelectAllAsync() {
            return base.Channel.SelectAllAsync();
        }
        
        public WorldMap.Model.RoleData SelectById(object id) {
            return base.Channel.SelectById(id);
        }
        
        public System.Threading.Tasks.Task<WorldMap.Model.RoleData> SelectByIdAsync(object id) {
            return base.Channel.SelectByIdAsync(id);
        }
    }
}
