//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldMap.Prism.CountryDataServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CountryData", Namespace="http://schemas.datacontract.org/2004/07/WorldMap.Model")]
    [System.SerializableAttribute()]
    public partial class CountryData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContinentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCapitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsIslandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WorldMap.Prism.CountryDataServiceReference.OverseasTerritoriesData[] overseasTerritoriesDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WorldMap.Prism.CountryDataServiceReference.StateData[] stateDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContinentId {
            get {
                return this.ContinentIdField;
            }
            set {
                if ((this.ContinentIdField.Equals(value) != true)) {
                    this.ContinentIdField = value;
                    this.RaisePropertyChanged("ContinentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCapital {
            get {
                return this.CountryCapitalField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCapitalField, value) != true)) {
                    this.CountryCapitalField = value;
                    this.RaisePropertyChanged("CountryCapital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId {
            get {
                return this.CountryIdField;
            }
            set {
                if ((this.CountryIdField.Equals(value) != true)) {
                    this.CountryIdField = value;
                    this.RaisePropertyChanged("CountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsIsland {
            get {
                return this.IsIslandField;
            }
            set {
                if ((this.IsIslandField.Equals(value) != true)) {
                    this.IsIslandField = value;
                    this.RaisePropertyChanged("IsIsland");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorldMap.Prism.CountryDataServiceReference.OverseasTerritoriesData[] overseasTerritoriesData {
            get {
                return this.overseasTerritoriesDataField;
            }
            set {
                if ((object.ReferenceEquals(this.overseasTerritoriesDataField, value) != true)) {
                    this.overseasTerritoriesDataField = value;
                    this.RaisePropertyChanged("overseasTerritoriesData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorldMap.Prism.CountryDataServiceReference.StateData[] stateData {
            get {
                return this.stateDataField;
            }
            set {
                if ((object.ReferenceEquals(this.stateDataField, value) != true)) {
                    this.stateDataField = value;
                    this.RaisePropertyChanged("stateData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OverseasTerritoriesData", Namespace="http://schemas.datacontract.org/2004/07/WorldMap.Model")]
    [System.SerializableAttribute()]
    public partial class OverseasTerritoriesData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OverseasTerritoriesIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OverseasTerritoriesNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId {
            get {
                return this.CountryIdField;
            }
            set {
                if ((this.CountryIdField.Equals(value) != true)) {
                    this.CountryIdField = value;
                    this.RaisePropertyChanged("CountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OverseasTerritoriesId {
            get {
                return this.OverseasTerritoriesIdField;
            }
            set {
                if ((this.OverseasTerritoriesIdField.Equals(value) != true)) {
                    this.OverseasTerritoriesIdField = value;
                    this.RaisePropertyChanged("OverseasTerritoriesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OverseasTerritoriesName {
            get {
                return this.OverseasTerritoriesNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OverseasTerritoriesNameField, value) != true)) {
                    this.OverseasTerritoriesNameField = value;
                    this.RaisePropertyChanged("OverseasTerritoriesName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StateData", Namespace="http://schemas.datacontract.org/2004/07/WorldMap.Model")]
    [System.SerializableAttribute()]
    public partial class StateData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateCapitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WorldMap.Prism.CountryDataServiceReference.CityData[] cityDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId {
            get {
                return this.CountryIdField;
            }
            set {
                if ((this.CountryIdField.Equals(value) != true)) {
                    this.CountryIdField = value;
                    this.RaisePropertyChanged("CountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateCapital {
            get {
                return this.StateCapitalField;
            }
            set {
                if ((object.ReferenceEquals(this.StateCapitalField, value) != true)) {
                    this.StateCapitalField = value;
                    this.RaisePropertyChanged("StateCapital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateId {
            get {
                return this.StateIdField;
            }
            set {
                if ((this.StateIdField.Equals(value) != true)) {
                    this.StateIdField = value;
                    this.RaisePropertyChanged("StateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateName {
            get {
                return this.StateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StateNameField, value) != true)) {
                    this.StateNameField = value;
                    this.RaisePropertyChanged("StateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorldMap.Prism.CountryDataServiceReference.CityData[] cityData {
            get {
                return this.cityDataField;
            }
            set {
                if ((object.ReferenceEquals(this.cityDataField, value) != true)) {
                    this.cityDataField = value;
                    this.RaisePropertyChanged("cityData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CityData", Namespace="http://schemas.datacontract.org/2004/07/WorldMap.Model")]
    [System.SerializableAttribute()]
    public partial class CityData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateId {
            get {
                return this.StateIdField;
            }
            set {
                if ((this.StateIdField.Equals(value) != true)) {
                    this.StateIdField = value;
                    this.RaisePropertyChanged("StateId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CountryDataServiceReference.ICountryDataService")]
    public interface ICountryDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryDataService/Insert", ReplyAction="http://tempuri.org/ICountryDataService/InsertResponse")]
        void Insert(WorldMap.Prism.CountryDataServiceReference.CountryData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryDataService/Insert", ReplyAction="http://tempuri.org/ICountryDataService/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync(WorldMap.Prism.CountryDataServiceReference.CountryData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryDataService/Delete", ReplyAction="http://tempuri.org/ICountryDataService/DeleteResponse")]
        void Delete(WorldMap.Prism.CountryDataServiceReference.CountryData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryDataService/Delete", ReplyAction="http://tempuri.org/ICountryDataService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(WorldMap.Prism.CountryDataServiceReference.CountryData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryDataService/Update", ReplyAction="http://tempuri.org/ICountryDataService/UpdateResponse")]
        void Update(WorldMap.Prism.CountryDataServiceReference.CountryData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryDataService/Update", ReplyAction="http://tempuri.org/ICountryDataService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(WorldMap.Prism.CountryDataServiceReference.CountryData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryDataService/SelectAll", ReplyAction="http://tempuri.org/ICountryDataService/SelectAllResponse")]
        WorldMap.Prism.CountryDataServiceReference.CountryData[] SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryDataService/SelectAll", ReplyAction="http://tempuri.org/ICountryDataService/SelectAllResponse")]
        System.Threading.Tasks.Task<WorldMap.Prism.CountryDataServiceReference.CountryData[]> SelectAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryDataService/SelectById", ReplyAction="http://tempuri.org/ICountryDataService/SelectByIdResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorldMap.Prism.CountryDataServiceReference.CountryData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorldMap.Prism.CountryDataServiceReference.OverseasTerritoriesData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorldMap.Prism.CountryDataServiceReference.OverseasTerritoriesData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorldMap.Prism.CountryDataServiceReference.StateData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorldMap.Prism.CountryDataServiceReference.StateData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorldMap.Prism.CountryDataServiceReference.CityData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorldMap.Prism.CountryDataServiceReference.CityData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorldMap.Prism.CountryDataServiceReference.CountryData[]))]
        WorldMap.Prism.CountryDataServiceReference.CountryData SelectById(object id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryDataService/SelectById", ReplyAction="http://tempuri.org/ICountryDataService/SelectByIdResponse")]
        System.Threading.Tasks.Task<WorldMap.Prism.CountryDataServiceReference.CountryData> SelectByIdAsync(object id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICountryDataServiceChannel : WorldMap.Prism.CountryDataServiceReference.ICountryDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CountryDataServiceClient : System.ServiceModel.ClientBase<WorldMap.Prism.CountryDataServiceReference.ICountryDataService>, WorldMap.Prism.CountryDataServiceReference.ICountryDataService {
        
        public CountryDataServiceClient() {
        }
        
        public CountryDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CountryDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CountryDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CountryDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Insert(WorldMap.Prism.CountryDataServiceReference.CountryData entity) {
            base.Channel.Insert(entity);
        }
        
        public System.Threading.Tasks.Task InsertAsync(WorldMap.Prism.CountryDataServiceReference.CountryData entity) {
            return base.Channel.InsertAsync(entity);
        }
        
        public void Delete(WorldMap.Prism.CountryDataServiceReference.CountryData entity) {
            base.Channel.Delete(entity);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(WorldMap.Prism.CountryDataServiceReference.CountryData entity) {
            return base.Channel.DeleteAsync(entity);
        }
        
        public void Update(WorldMap.Prism.CountryDataServiceReference.CountryData entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(WorldMap.Prism.CountryDataServiceReference.CountryData entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public WorldMap.Prism.CountryDataServiceReference.CountryData[] SelectAll() {
            return base.Channel.SelectAll();
        }
        
        public System.Threading.Tasks.Task<WorldMap.Prism.CountryDataServiceReference.CountryData[]> SelectAllAsync() {
            return base.Channel.SelectAllAsync();
        }
        
        public WorldMap.Prism.CountryDataServiceReference.CountryData SelectById(object id) {
            return base.Channel.SelectById(id);
        }
        
        public System.Threading.Tasks.Task<WorldMap.Prism.CountryDataServiceReference.CountryData> SelectByIdAsync(object id) {
            return base.Channel.SelectByIdAsync(id);
        }
    }
}
