//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldMap.MVC.CityDataServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CityDataServiceReference.ICityDataService")]
    public interface ICityDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICityDataService/Insert", ReplyAction="http://tempuri.org/ICityDataService/InsertResponse")]
        void Insert(WorldMap.Model.CityData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICityDataService/Insert", ReplyAction="http://tempuri.org/ICityDataService/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync(WorldMap.Model.CityData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICityDataService/Delete", ReplyAction="http://tempuri.org/ICityDataService/DeleteResponse")]
        void Delete(WorldMap.Model.CityData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICityDataService/Delete", ReplyAction="http://tempuri.org/ICityDataService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(WorldMap.Model.CityData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICityDataService/Update", ReplyAction="http://tempuri.org/ICityDataService/UpdateResponse")]
        void Update(WorldMap.Model.CityData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICityDataService/Update", ReplyAction="http://tempuri.org/ICityDataService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(WorldMap.Model.CityData entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICityDataService/SelectAll", ReplyAction="http://tempuri.org/ICityDataService/SelectAllResponse")]
        WorldMap.Model.CityData[] SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICityDataService/SelectAll", ReplyAction="http://tempuri.org/ICityDataService/SelectAllResponse")]
        System.Threading.Tasks.Task<WorldMap.Model.CityData[]> SelectAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICityDataService/SelectById", ReplyAction="http://tempuri.org/ICityDataService/SelectByIdResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorldMap.Model.CityData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorldMap.Model.CityData[]))]
        WorldMap.Model.CityData SelectById(object id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICityDataService/SelectById", ReplyAction="http://tempuri.org/ICityDataService/SelectByIdResponse")]
        System.Threading.Tasks.Task<WorldMap.Model.CityData> SelectByIdAsync(object id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICityDataServiceChannel : WorldMap.MVC.CityDataServiceReference.ICityDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CityDataServiceClient : System.ServiceModel.ClientBase<WorldMap.MVC.CityDataServiceReference.ICityDataService>, WorldMap.MVC.CityDataServiceReference.ICityDataService {
        
        public CityDataServiceClient() {
        }
        
        public CityDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CityDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CityDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CityDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Insert(WorldMap.Model.CityData entity) {
            base.Channel.Insert(entity);
        }
        
        public System.Threading.Tasks.Task InsertAsync(WorldMap.Model.CityData entity) {
            return base.Channel.InsertAsync(entity);
        }
        
        public void Delete(WorldMap.Model.CityData entity) {
            base.Channel.Delete(entity);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(WorldMap.Model.CityData entity) {
            return base.Channel.DeleteAsync(entity);
        }
        
        public void Update(WorldMap.Model.CityData entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(WorldMap.Model.CityData entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public WorldMap.Model.CityData[] SelectAll() {
            return base.Channel.SelectAll();
        }
        
        public System.Threading.Tasks.Task<WorldMap.Model.CityData[]> SelectAllAsync() {
            return base.Channel.SelectAllAsync();
        }
        
        public WorldMap.Model.CityData SelectById(object id) {
            return base.Channel.SelectById(id);
        }
        
        public System.Threading.Tasks.Task<WorldMap.Model.CityData> SelectByIdAsync(object id) {
            return base.Channel.SelectByIdAsync(id);
        }
    }
}
